package wisoft.pack.data.pojo;

public class PackPackages extends PackageInfo{


	private String packPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String archiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private Integer state;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PACK_PACKAGES.pack_person
	 * @return  the value of PACK_PACKAGES.pack_person
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getPackPerson() {
		return packPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PACK_PACKAGES.pack_person
	 * @param packPerson  the value for PACK_PACKAGES.pack_person
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setPackPerson(String packPerson) {
		this.packPerson = packPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PACK_PACKAGES.create_time
	 * @return  the value of PACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PACK_PACKAGES.create_time
	 * @param createTime  the value for PACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PACK_PACKAGES.archive_time
	 * @return  the value of PACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getArchiveTime() {
		return archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PACK_PACKAGES.archive_time
	 * @param archiveTime  the value for PACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setArchiveTime(String archiveTime) {
		this.archiveTime = archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PACK_PACKAGES.state
	 * @return  the value of PACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PACK_PACKAGES.state
	 * @param state  the value for PACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setState(Integer state) {
		this.state = state;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.getModuleName()+"("+this.getModuleCode()+")"+this.getModuleVer();
	}
}