package wisoft.pack.data.mapper;

import wisoft.pack.pojo.PackPackages;

public interface PackPackagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_PACKAGES
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insert(PackPackages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_PACKAGES
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insertSelective(PackPackages record);
}