package wisoft.pack.data.mapper;

import wisoft.pack.pojo.UnpackServers;

public interface UnpackServersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_SERVERS
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insert(UnpackServers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_SERVERS
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insertSelective(UnpackServers record);
}