package wisoft.pack.data.mapper;

import wisoft.pack.data.pojo.UnpackServers;

public interface UnpackServersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_SERVERS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insert(UnpackServers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_SERVERS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insertSelective(UnpackServers record);
}