package wisoft.pack.data.mapper;

import wisoft.pack.pojo.WisoftPackageClass;

public interface WisoftPackageClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WISOFT_PACKAGE_CLASS
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insert(WisoftPackageClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WISOFT_PACKAGE_CLASS
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insertSelective(WisoftPackageClass record);
}