package wisoft.pack.data.mapper;

import wisoft.pack.data.pojo.WisoftPackageClass;

public interface WisoftPackageClassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WISOFT_PACKAGE_CLASS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insert(WisoftPackageClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WISOFT_PACKAGE_CLASS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insertSelective(WisoftPackageClass record);
	
	WisoftPackageClass selectUnPackClass();
}