package wisoft.pack.data.mapper;

import wisoft.pack.pojo.UnpackPackages;

public interface UnpackPackagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_PACKAGES
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insert(UnpackPackages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_PACKAGES
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insertSelective(UnpackPackages record);
}