package wisoft.pack.data.mapper;

import wisoft.pack.data.pojo.UnpackServerDb;

public interface UnpackServerDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_SERVER_DB
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insert(UnpackServerDb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_SERVER_DB
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insertSelective(UnpackServerDb record);
}