package wisoft.pack.data.mapper;

import wisoft.pack.pojo.UnpackServerDb;

public interface UnpackServerDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_SERVER_DB
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insert(UnpackServerDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNPACK_SERVER_DB
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    int insertSelective(UnpackServerDb record);
}