package wisoft.pack.data.mapper;

import wisoft.pack.data.pojo.UnpackPackages;

public interface UnpackPackagesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_PACKAGES
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insert(UnpackPackages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UNPACK_PACKAGES
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insertSelective(UnpackPackages record);
	
	UnpackPackages selectUPakageByClassId(String parent_class_id);
}