package wisoft.pack.data.mapper;

import java.util.List;

import wisoft.pack.data.dao.PackageClassInfo;
import wisoft.pack.data.pojo.WisoftPackageClass;

public interface WisoftPackageClassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WISOFT_PACKAGE_CLASS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insert(WisoftPackageClass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WISOFT_PACKAGE_CLASS
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	int insertSelective(WisoftPackageClass record);
	
	List<PackageClassInfo> selectUnPackClassWithPack();
	
	WisoftPackageClass selectClassInfoById(String id);
	
	PackageClassInfo selectClassById(String id);
	List<PackageClassInfo> selectClassByParentId(String parent_id);
}