package wisoft.pack.data.pojo;

public class UnpackPackages extends PackageInfo {

	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	private String unpackPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.create_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.update_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	private String archiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.state
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.ID
	 * @return  the value of UNPACK_PACKAGES.ID
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.ID
	 * @param id  the value for UNPACK_PACKAGES.ID
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.package_name
	 * @return  the value of UNPACK_PACKAGES.package_name
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.unpack_person
	 * @return  the value of UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public String getUnpackPerson() {
		return unpackPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.unpack_person
	 * @param unpackPerson  the value for UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setUnpackPerson(String unpackPerson) {
		this.unpackPerson = unpackPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.create_time
	 * @return  the value of UNPACK_PACKAGES.create_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.create_time
	 * @param createTime  the value for UNPACK_PACKAGES.create_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.update_time
	 * @return  the value of UNPACK_PACKAGES.update_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.update_time
	 * @param updateTime  the value for UNPACK_PACKAGES.update_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.archive_time
	 * @return  the value of UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public String getArchiveTime() {
		return archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.archive_time
	 * @param archiveTime  the value for UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setArchiveTime(String archiveTime) {
		this.archiveTime = archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.state
	 * @return  the value of UNPACK_PACKAGES.state
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.state
	 * @param state  the value for UNPACK_PACKAGES.state
	 * @mbggenerated  Thu Jun 13 10:44:42 CST 2013
	 */
	public void setState(Integer state) {
		this.state = state;
	}

}