package wisoft.pack.data.pojo;

public class UnpackServers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String wimsProjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.wims_project_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String wimsProjectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_app_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverAppPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.unpack_server_db_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String unpackServerDbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_port
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_username
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverUsername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_password
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.wsm_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String wsmPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_SERVERS.server_ip
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String serverIp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.ID
	 * @return  the value of UNPACK_SERVERS.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.ID
	 * @param id  the value for UNPACK_SERVERS.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_name
	 * @return  the value of UNPACK_SERVERS.server_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_name
	 * @param serverName  the value for UNPACK_SERVERS.server_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.wims_project_id
	 * @return  the value of UNPACK_SERVERS.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getWimsProjectId() {
		return wimsProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.wims_project_id
	 * @param wimsProjectId  the value for UNPACK_SERVERS.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setWimsProjectId(String wimsProjectId) {
		this.wimsProjectId = wimsProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.wims_project_name
	 * @return  the value of UNPACK_SERVERS.wims_project_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getWimsProjectName() {
		return wimsProjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.wims_project_name
	 * @param wimsProjectName  the value for UNPACK_SERVERS.wims_project_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setWimsProjectName(String wimsProjectName) {
		this.wimsProjectName = wimsProjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_app_path
	 * @return  the value of UNPACK_SERVERS.server_app_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerAppPath() {
		return serverAppPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_app_path
	 * @param serverAppPath  the value for UNPACK_SERVERS.server_app_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerAppPath(String serverAppPath) {
		this.serverAppPath = serverAppPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.unpack_server_db_id
	 * @return  the value of UNPACK_SERVERS.unpack_server_db_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getUnpackServerDbId() {
		return unpackServerDbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.unpack_server_db_id
	 * @param unpackServerDbId  the value for UNPACK_SERVERS.unpack_server_db_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setUnpackServerDbId(String unpackServerDbId) {
		this.unpackServerDbId = unpackServerDbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_port
	 * @return  the value of UNPACK_SERVERS.server_port
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerPort() {
		return serverPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_port
	 * @param serverPort  the value for UNPACK_SERVERS.server_port
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerPort(String serverPort) {
		this.serverPort = serverPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_username
	 * @return  the value of UNPACK_SERVERS.server_username
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerUsername() {
		return serverUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_username
	 * @param serverUsername  the value for UNPACK_SERVERS.server_username
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerUsername(String serverUsername) {
		this.serverUsername = serverUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_password
	 * @return  the value of UNPACK_SERVERS.server_password
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerPassword() {
		return serverPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_password
	 * @param serverPassword  the value for UNPACK_SERVERS.server_password
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerPassword(String serverPassword) {
		this.serverPassword = serverPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.wsm_path
	 * @return  the value of UNPACK_SERVERS.wsm_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getWsmPath() {
		return wsmPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.wsm_path
	 * @param wsmPath  the value for UNPACK_SERVERS.wsm_path
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setWsmPath(String wsmPath) {
		this.wsmPath = wsmPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_SERVERS.server_ip
	 * @return  the value of UNPACK_SERVERS.server_ip
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getServerIp() {
		return serverIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_SERVERS.server_ip
	 * @param serverIp  the value for UNPACK_SERVERS.server_ip
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}
}