package wisoft.pack.data.pojo;

public class UnpackPackages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.package_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.module_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String moduleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.module_code
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String moduleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.module_ver
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String moduleVer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.test_number
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private Integer testNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.package_publishdate
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String packagePublishdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String unpackPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.update_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String archiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.package_class_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String packageClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String wimsProjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UNPACK_PACKAGES.package_file_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	private String packageFileId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.ID
	 * @return  the value of UNPACK_PACKAGES.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.ID
	 * @param id  the value for UNPACK_PACKAGES.ID
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.package_name
	 * @return  the value of UNPACK_PACKAGES.package_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.package_name
	 * @param packageName  the value for UNPACK_PACKAGES.package_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.module_name
	 * @return  the value of UNPACK_PACKAGES.module_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getModuleName() {
		return moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.module_name
	 * @param moduleName  the value for UNPACK_PACKAGES.module_name
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.module_code
	 * @return  the value of UNPACK_PACKAGES.module_code
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getModuleCode() {
		return moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.module_code
	 * @param moduleCode  the value for UNPACK_PACKAGES.module_code
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.module_ver
	 * @return  the value of UNPACK_PACKAGES.module_ver
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getModuleVer() {
		return moduleVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.module_ver
	 * @param moduleVer  the value for UNPACK_PACKAGES.module_ver
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setModuleVer(String moduleVer) {
		this.moduleVer = moduleVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.test_number
	 * @return  the value of UNPACK_PACKAGES.test_number
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public Integer getTestNumber() {
		return testNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.test_number
	 * @param testNumber  the value for UNPACK_PACKAGES.test_number
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setTestNumber(Integer testNumber) {
		this.testNumber = testNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.package_publishdate
	 * @return  the value of UNPACK_PACKAGES.package_publishdate
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getPackagePublishdate() {
		return packagePublishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.package_publishdate
	 * @param packagePublishdate  the value for UNPACK_PACKAGES.package_publishdate
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setPackagePublishdate(String packagePublishdate) {
		this.packagePublishdate = packagePublishdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.unpack_person
	 * @return  the value of UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getUnpackPerson() {
		return unpackPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.unpack_person
	 * @param unpackPerson  the value for UNPACK_PACKAGES.unpack_person
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setUnpackPerson(String unpackPerson) {
		this.unpackPerson = unpackPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.create_time
	 * @return  the value of UNPACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.create_time
	 * @param createTime  the value for UNPACK_PACKAGES.create_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.update_time
	 * @return  the value of UNPACK_PACKAGES.update_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.update_time
	 * @param updateTime  the value for UNPACK_PACKAGES.update_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.archive_time
	 * @return  the value of UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getArchiveTime() {
		return archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.archive_time
	 * @param archiveTime  the value for UNPACK_PACKAGES.archive_time
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setArchiveTime(String archiveTime) {
		this.archiveTime = archiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.state
	 * @return  the value of UNPACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.state
	 * @param state  the value for UNPACK_PACKAGES.state
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.package_class_id
	 * @return  the value of UNPACK_PACKAGES.package_class_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getPackageClassId() {
		return packageClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.package_class_id
	 * @param packageClassId  the value for UNPACK_PACKAGES.package_class_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setPackageClassId(String packageClassId) {
		this.packageClassId = packageClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.wims_project_id
	 * @return  the value of UNPACK_PACKAGES.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getWimsProjectId() {
		return wimsProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.wims_project_id
	 * @param wimsProjectId  the value for UNPACK_PACKAGES.wims_project_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setWimsProjectId(String wimsProjectId) {
		this.wimsProjectId = wimsProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UNPACK_PACKAGES.package_file_id
	 * @return  the value of UNPACK_PACKAGES.package_file_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public String getPackageFileId() {
		return packageFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UNPACK_PACKAGES.package_file_id
	 * @param packageFileId  the value for UNPACK_PACKAGES.package_file_id
	 * @mbggenerated  Sun Jun 09 13:16:06 CST 2013
	 */
	public void setPackageFileId(String packageFileId) {
		this.packageFileId = packageFileId;
	}
}