package wisoft.pack.pojo;

public class UnpackServerDb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.unpack_server_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String unpackServerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.username
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.password
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.port
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.IP
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.dbinstance
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String dbinstance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UNPACK_SERVER_DB.dbtype
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String dbtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.ID
     *
     * @return the value of UNPACK_SERVER_DB.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.ID
     *
     * @param id the value for UNPACK_SERVER_DB.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.unpack_server_id
     *
     * @return the value of UNPACK_SERVER_DB.unpack_server_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getUnpackServerId() {
        return unpackServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.unpack_server_id
     *
     * @param unpackServerId the value for UNPACK_SERVER_DB.unpack_server_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setUnpackServerId(String unpackServerId) {
        this.unpackServerId = unpackServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.username
     *
     * @return the value of UNPACK_SERVER_DB.username
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.username
     *
     * @param username the value for UNPACK_SERVER_DB.username
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.password
     *
     * @return the value of UNPACK_SERVER_DB.password
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.password
     *
     * @param password the value for UNPACK_SERVER_DB.password
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.port
     *
     * @return the value of UNPACK_SERVER_DB.port
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.port
     *
     * @param port the value for UNPACK_SERVER_DB.port
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.IP
     *
     * @return the value of UNPACK_SERVER_DB.IP
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.IP
     *
     * @param ip the value for UNPACK_SERVER_DB.IP
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.dbinstance
     *
     * @return the value of UNPACK_SERVER_DB.dbinstance
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getDbinstance() {
        return dbinstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.dbinstance
     *
     * @param dbinstance the value for UNPACK_SERVER_DB.dbinstance
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setDbinstance(String dbinstance) {
        this.dbinstance = dbinstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UNPACK_SERVER_DB.dbtype
     *
     * @return the value of UNPACK_SERVER_DB.dbtype
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getDbtype() {
        return dbtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UNPACK_SERVER_DB.dbtype
     *
     * @param dbtype the value for UNPACK_SERVER_DB.dbtype
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype;
    }
}