package wisoft.pack.pojo;

public class WisoftPackageClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.class_name
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.parent_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.isdefault
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private Integer isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.order_no
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WISOFT_PACKAGE_CLASS.class_type
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    private Integer classType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.ID
     *
     * @return the value of WISOFT_PACKAGE_CLASS.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.ID
     *
     * @param id the value for WISOFT_PACKAGE_CLASS.ID
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.class_name
     *
     * @return the value of WISOFT_PACKAGE_CLASS.class_name
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.class_name
     *
     * @param className the value for WISOFT_PACKAGE_CLASS.class_name
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.parent_id
     *
     * @return the value of WISOFT_PACKAGE_CLASS.parent_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.parent_id
     *
     * @param parentId the value for WISOFT_PACKAGE_CLASS.parent_id
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.isdefault
     *
     * @return the value of WISOFT_PACKAGE_CLASS.isdefault
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.isdefault
     *
     * @param isdefault the value for WISOFT_PACKAGE_CLASS.isdefault
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.order_no
     *
     * @return the value of WISOFT_PACKAGE_CLASS.order_no
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.order_no
     *
     * @param orderNo the value for WISOFT_PACKAGE_CLASS.order_no
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WISOFT_PACKAGE_CLASS.class_type
     *
     * @return the value of WISOFT_PACKAGE_CLASS.class_type
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public Integer getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WISOFT_PACKAGE_CLASS.class_type
     *
     * @param classType the value for WISOFT_PACKAGE_CLASS.class_type
     *
     * @mbggenerated Sat Jun 08 15:31:18 CST 2013
     */
    public void setClassType(Integer classType) {
        this.classType = classType;
    }
}