package com.wisoft.wims;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWimsManagerWSPortType", targetNamespace = "http://www.springframework.org/schema/beans")
public interface IWimsManagerWSPortType {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByServicesInParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByServicesInParames")
	@ResponseWrapper(localName = "findTaskByServicesInParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByServicesInParamesResponse")
	public ResultReturnByArray findTaskByServicesInParames(
			@WebParam(name = "arg0", targetNamespace = "")
			TaskServicesIn arg0, @WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByMilestone1", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByMilestone1")
	@ResponseWrapper(localName = "findTaskByMilestone1Response", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByMilestone1Response")
	public ResultReturnByArray findTaskByMilestone1(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2, @WebParam(name = "arg3", targetNamespace = "")
			int arg3);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultOwnerListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonListByDepCode", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonListByDepCode")
	@ResponseWrapper(localName = "findPersonListByDepCodeResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonListByDepCodeResponse")
	public ResultOwnerListReturn findPersonListByDepCode(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateMilestoneIdByTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneIdByTask")
	@ResponseWrapper(localName = "updateMilestoneIdByTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneIdByTaskResponse")
	public TaskReturn updateMilestoneIdByTask(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTrack")
	@ResponseWrapper(localName = "deleteTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTrackResponse")
	public BaseReturn deleteTrack(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsSingleIssueTracking arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.WimsTaskmgr
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByTaskId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByTaskId")
	@ResponseWrapper(localName = "findTaskByTaskIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByTaskIdResponse")
	public WimsTaskmgr findTaskByTaskId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "mohuSearch", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.MohuSearch")
	@ResponseWrapper(localName = "mohuSearchResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.MohuSearchResponse")
	public ResultReturn mohuSearch(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateMilestoneIdByTasks", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneIdByTasks")
	@ResponseWrapper(localName = "updateMilestoneIdByTasksResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneIdByTasksResponse")
	public TaskReturn updateMilestoneIdByTasks(
			@WebParam(name = "arg0", targetNamespace = "")
			List<WimsTaskmgr> arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultOwnerListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonByTeamNameIsLeader", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamNameIsLeader")
	@ResponseWrapper(localName = "findPersonByTeamNameIsLeaderResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamNameIsLeaderResponse")
	public ResultOwnerListReturn findPersonByTeamNameIsLeader(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveProInfo")
	@ResponseWrapper(localName = "saveProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveProInfoResponse")
	public BaseReturn saveProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsProInfo arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTask")
	@ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTaskResponse")
	public BaseReturn deleteTask(@WebParam(name = "arg0", targetNamespace = "")
	WimsTaskmgr arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findLogsByTrackingId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindLogsByTrackingId")
	@ResponseWrapper(localName = "findLogsByTrackingIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindLogsByTrackingIdResponse")
	public ResultListReturn findLogsByTrackingId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "cloTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.CloTrack")
	@ResponseWrapper(localName = "cloTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.CloTrackResponse")
	public BaseReturn cloTrack(@WebParam(name = "arg0", targetNamespace = "")
	List<WimsSingleIssueTracking> arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			List<WimsStepInfo> arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultOwnerListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonByTeamNameIsLeaderAndDep", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamNameIsLeaderAndDep")
	@ResponseWrapper(localName = "findPersonByTeamNameIsLeaderAndDepResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamNameIsLeaderAndDepResponse")
	public ResultOwnerListReturn findPersonByTeamNameIsLeaderAndDep(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultPersonByGroupReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTeamByLeaderTeamName", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTeamByLeaderTeamName")
	@ResponseWrapper(localName = "findTeamByLeaderTeamNameResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTeamByLeaderTeamNameResponse")
	public ResultPersonByGroupReturn findTeamByLeaderTeamName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "finishTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FinishTask")
	@ResponseWrapper(localName = "finishTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FinishTaskResponse")
	public BaseReturn finishTask(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateMilestone", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestone")
	@ResponseWrapper(localName = "updateMilestoneResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneResponse")
	public ResultReturn updateMilestone(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsMilestone arg0, @WebParam(name = "arg1", targetNamespace = "")
			List<OmsPerson> arg1);

	/**
	 * 
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllProInfo")
	@ResponseWrapper(localName = "findAllProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllProInfoResponse")
	public ResultReturnByArray findAllProInfo();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteProInfo")
	@ResponseWrapper(localName = "deleteProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteProInfoResponse")
	public BaseReturn deleteProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsProInfo arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findMilestoneByServicesInParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByServicesInParames")
	@ResponseWrapper(localName = "findMilestoneByServicesInParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByServicesInParamesResponse")
	public ResultReturn findMilestoneByServicesInParames(
			@WebParam(name = "arg0", targetNamespace = "")
			MilestoneServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findNewTaskNumber", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindNewTaskNumber")
	@ResponseWrapper(localName = "findNewTaskNumberResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindNewTaskNumberResponse")
	public String findNewTaskNumber();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateMilestoneByTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneByTask")
	@ResponseWrapper(localName = "updateMilestoneByTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateMilestoneByTaskResponse")
	public TaskReturn updateMilestoneByTask(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsTaskmgr arg0, @WebParam(name = "arg1", targetNamespace = "")
			WimsMilestone arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findMilestoneByProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByProInfo")
	@ResponseWrapper(localName = "findMilestoneByProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByProInfoResponse")
	public ResultReturnByArray findMilestoneByProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByProInfo")
	@ResponseWrapper(localName = "findTaskByProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByProInfoResponse")
	public ResultReturnByArray findTaskByProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2, @WebParam(name = "arg3", targetNamespace = "")
			int arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "finishTasks", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FinishTasks")
	@ResponseWrapper(localName = "finishTasksResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FinishTasksResponse")
	public BaseReturn finishTasks(
			@WebParam(name = "arg0", targetNamespace = "")
			List<WimsTaskmgr> arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveAttachment", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveAttachment")
	@ResponseWrapper(localName = "saveAttachmentResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveAttachmentResponse")
	public BaseReturn saveAttachment(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsAttachMent arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateBatchTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateBatchTrack")
	@ResponseWrapper(localName = "updateBatchTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateBatchTrackResponse")
	public BaseReturn updateBatchTrack(
			@WebParam(name = "arg0", targetNamespace = "")
			List<WimsSingleIssueTracking> arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			List<WimsSingleIssueTracking> arg1,
			@WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @return returns com.wisoft.wims.PersonArrayReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllPerson", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllPerson")
	@ResponseWrapper(localName = "findAllPersonResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllPersonResponse")
	public PersonArrayReturn findAllPerson();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultPersonListByProInfoReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonListByProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonListByProInfo")
	@ResponseWrapper(localName = "findPersonListByProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonListByProInfoResponse")
	public ResultPersonListByProInfoReturn findPersonListByProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			List<SystemZdlist> arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateCilentInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateCilentInfo")
	@ResponseWrapper(localName = "updateCilentInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateCilentInfoResponse")
	public BaseReturn updateCilentInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsCilentInfo arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ProInfoReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findProInfoByServicesInParamesAndAdvanced", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindProInfoByServicesInParamesAndAdvanced")
	@ResponseWrapper(localName = "findProInfoByServicesInParamesAndAdvancedResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindProInfoByServicesInParamesAndAdvancedResponse")
	public ProInfoReturn findProInfoByServicesInParamesAndAdvanced(
			@WebParam(name = "arg0", targetNamespace = "")
			ProInfoServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.TrackReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTrackByTrackId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackByTrackId")
	@ResponseWrapper(localName = "findTrackByTrackIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackByTrackIdResponse")
	public TrackReturn findTrackByTrackId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "startTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.StartTask")
	@ResponseWrapper(localName = "startTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.StartTaskResponse")
	public BaseReturn startTask(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTrack")
	@ResponseWrapper(localName = "updateTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTrackResponse")
	public BaseReturn updateTrack(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsSingleIssueTracking arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			WimsStepInfo arg1, @WebParam(name = "arg2", targetNamespace = "")
			List<OmsPerson> arg2);

	/**
	 * 
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllWimsProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllWimsProInfo")
	@ResponseWrapper(localName = "findAllWimsProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllWimsProInfoResponse")
	public ResultReturnByArray findAllWimsProInfo();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.PersonListByTaskAndTrackIdReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskPersonInfoByTrackId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskPersonInfoByTrackId")
	@ResponseWrapper(localName = "findTaskPersonInfoByTrackIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskPersonInfoByTrackIdResponse")
	public PersonListByTaskAndTrackIdReturn findTaskPersonInfoByTrackId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTrack")
	@ResponseWrapper(localName = "saveTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTrackResponse")
	public BaseReturn saveTrack(@WebParam(name = "arg0", targetNamespace = "")
	WimsSingleIssueTracking arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			WimsStepInfo arg1, @WebParam(name = "arg2", targetNamespace = "")
			List<OmsPerson> arg2,
			@WebParam(name = "arg3", targetNamespace = "")
			List<WimsAttachMent> arg3);

	/**
	 * 
	 */
	@WebMethod
	@RequestWrapper(localName = "sendWimsTaskMgrMailByTimer", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SendWimsTaskMgrMailByTimer")
	@ResponseWrapper(localName = "sendWimsTaskMgrMailByTimerResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SendWimsTaskMgrMailByTimerResponse")
	public void sendWimsTaskMgrMailByTimer();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.TrackReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findFinishWimsTrackByVer", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindFinishWimsTrackByVer")
	@ResponseWrapper(localName = "findFinishWimsTrackByVerResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindFinishWimsTrackByVerResponse")
	public TrackReturn findFinishWimsTrackByVer(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.TaskHistoryReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskHistoryByTaskId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskHistoryByTaskId")
	@ResponseWrapper(localName = "findTaskHistoryByTaskIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskHistoryByTaskIdResponse")
	public TaskHistoryReturn findTaskHistoryByTaskId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findSNByPno", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindSNByPno")
	@ResponseWrapper(localName = "findSNByPnoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindSNByPnoResponse")
	public int findSNByPno(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTrackByServicesInParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackByServicesInParames")
	@ResponseWrapper(localName = "findTrackByServicesInParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackByServicesInParamesResponse")
	public ResultReturn findTrackByServicesInParames(
			@WebParam(name = "arg0", targetNamespace = "")
			TrackServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveCilentInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveCilentInfo")
	@ResponseWrapper(localName = "saveCilentInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveCilentInfoResponse")
	public BaseReturn saveCilentInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsCilentInfo arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findMilestoneByProInfo1", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByProInfo1")
	@ResponseWrapper(localName = "findMilestoneByProInfo1Response", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindMilestoneByProInfo1Response")
	public ResultReturnByArray findMilestoneByProInfo1(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2, @WebParam(name = "arg3", targetNamespace = "")
			int arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 */
	@WebMethod
	@RequestWrapper(localName = "saveTaskHistory", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTaskHistory")
	@ResponseWrapper(localName = "saveTaskHistoryResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTaskHistoryResponse")
	public void saveTaskHistory(@WebParam(name = "arg0", targetNamespace = "")
	String arg0, @WebParam(name = "arg1", targetNamespace = "")
	WimsTaskmgr arg1, @WebParam(name = "arg2", targetNamespace = "")
	WimsTaskmgr arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.PersonArrayReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonByTeamId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamId")
	@ResponseWrapper(localName = "findPersonByTeamIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamIdResponse")
	public PersonArrayReturn findPersonByTeamId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTrackStepsByTrackingId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackStepsByTrackingId")
	@ResponseWrapper(localName = "findTrackStepsByTrackingIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTrackStepsByTrackingIdResponse")
	public ResultReturn findTrackStepsByTrackingId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultWorkLoadStatisticsListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskWorkLoadStatisticsByParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskWorkLoadStatisticsByParames")
	@ResponseWrapper(localName = "findTaskWorkLoadStatisticsByParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskWorkLoadStatisticsByParamesResponse")
	public ResultWorkLoadStatisticsListReturn findTaskWorkLoadStatisticsByParames(
			@WebParam(name = "arg0", targetNamespace = "")
			WorkLoadStatisticsBySearchParamesServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.FileinfArrayReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAttachmentByTrackId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAttachmentByTrackId")
	@ResponseWrapper(localName = "findAttachmentByTrackIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAttachmentByTrackIdResponse")
	public FileinfArrayReturn findAttachmentByTrackId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByGroupIndexParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByGroupIndexParames")
	@ResponseWrapper(localName = "findTaskByGroupIndexParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByGroupIndexParamesResponse")
	public ResultReturnByArray findTaskByGroupIndexParames(
			@WebParam(name = "arg0", targetNamespace = "")
			TaskServicesIn arg0, @WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @param arg4
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateProInfo")
	@ResponseWrapper(localName = "updateProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateProInfoResponse")
	public BaseReturn updateProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsProInfo arg0, @WebParam(name = "arg1", targetNamespace = "")
			WimsProInfo arg1, @WebParam(name = "arg2", targetNamespace = "")
			ProChangeServicesIn arg2,
			@WebParam(name = "arg3", targetNamespace = "")
			String arg3, @WebParam(name = "arg4", targetNamespace = "")
			String arg4);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.PersonArrayReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findPersonByTeamName", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamName")
	@ResponseWrapper(localName = "findPersonByTeamNameResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindPersonByTeamNameResponse")
	public PersonArrayReturn findPersonByTeamName(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteTasks", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTasks")
	@ResponseWrapper(localName = "deleteTasksResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteTasksResponse")
	public BaseReturn deleteTasks(
			@WebParam(name = "arg0", targetNamespace = "")
			List<WimsTaskmgr> arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateWimsTrackStatus", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateWimsTrackStatus")
	@ResponseWrapper(localName = "updateWimsTrackStatusResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateWimsTrackStatusResponse")
	public BaseReturn updateWimsTrackStatus(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findWimsAttByTrackId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindWimsAttByTrackId")
	@ResponseWrapper(localName = "findWimsAttByTrackIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindWimsAttByTrackIdResponse")
	public ResultReturn findWimsAttByTrackId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByTrackId", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByTrackId")
	@ResponseWrapper(localName = "findTaskByTrackIdResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByTrackIdResponse")
	public TaskReturn findTaskByTrackId(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTask")
	@ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTaskResponse")
	public BaseReturn updateTask(@WebParam(name = "arg0", targetNamespace = "")
	OmsPerson arg0, @WebParam(name = "arg1", targetNamespace = "")
	WimsTaskmgr arg1, @WebParam(name = "arg2", targetNamespace = "")
	WimsTaskmgr arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "delMilestone", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelMilestone")
	@ResponseWrapper(localName = "delMilestoneResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelMilestoneResponse")
	public BaseReturn delMilestone(
			@WebParam(name = "arg0", targetNamespace = "")
			List<WimsMilestone> arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskByMilestone", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByMilestone")
	@ResponseWrapper(localName = "findTaskByMilestoneResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskByMilestoneResponse")
	public ResultReturnByArray findTaskByMilestone(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.WorkLoadStatisticsByProListReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findTaskWorkLoadStatisticsByPro", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskWorkLoadStatisticsByPro")
	@ResponseWrapper(localName = "findTaskWorkLoadStatisticsByProResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindTaskWorkLoadStatisticsByProResponse")
	public WorkLoadStatisticsByProListReturn findTaskWorkLoadStatisticsByPro(
			@WebParam(name = "arg0", targetNamespace = "")
			XMLGregorianCalendar arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			XMLGregorianCalendar arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "delAttachments", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelAttachments")
	@ResponseWrapper(localName = "delAttachmentsResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelAttachmentsResponse")
	public BaseReturn delAttachments(
			@WebParam(name = "arg0", targetNamespace = "")
			List<NfmFileinf> arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod(operationName = "updateTaskByIds_gl")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTaskByIds_gl", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTaskByIdsGl")
	@ResponseWrapper(localName = "updateTaskByIds_glResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTaskByIdsGlResponse")
	public TaskReturn updateTaskByIdsGl(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "delTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelTrack")
	@ResponseWrapper(localName = "delTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DelTrackResponse")
	public BaseReturn delTrack(@WebParam(name = "arg0", targetNamespace = "")
	List<WimsSingleIssueTracking> arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveTask", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTask")
	@ResponseWrapper(localName = "saveTaskResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveTaskResponse")
	public BaseReturn saveTask(@WebParam(name = "arg0", targetNamespace = "")
	WimsTaskmgr arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "printCilentInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintCilentInfo")
	@ResponseWrapper(localName = "printCilentInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintCilentInfoResponse")
	public BaseReturn printCilentInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			List<String> arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.TaskReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTaskByIds", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTaskByIds")
	@ResponseWrapper(localName = "updateTaskByIdsResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.UpdateTaskByIdsResponse")
	public TaskReturn updateTaskByIds(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0, @WebParam(name = "arg1", targetNamespace = "")
			String arg1, @WebParam(name = "arg2", targetNamespace = "")
			String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteCilentInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteCilentInfo")
	@ResponseWrapper(localName = "deleteCilentInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.DeleteCilentInfoResponse")
	public BaseReturn deleteCilentInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsCilentInfo arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "printTrack", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintTrack")
	@ResponseWrapper(localName = "printTrackResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintTrackResponse")
	public BaseReturn printTrack(@WebParam(name = "arg0", targetNamespace = "")
	List<String> arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveMilestone", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveMilestone")
	@ResponseWrapper(localName = "saveMilestoneResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.SaveMilestoneResponse")
	public ResultReturn saveMilestone(
			@WebParam(name = "arg0", targetNamespace = "")
			WimsMilestone arg0, @WebParam(name = "arg1", targetNamespace = "")
			List<OmsPerson> arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.ProInfoHistoryReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllProInfoHistory", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllProInfoHistory")
	@ResponseWrapper(localName = "findAllProInfoHistoryResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllProInfoHistoryResponse")
	public ProInfoHistoryReturn findAllProInfoHistory(
			@WebParam(name = "arg0", targetNamespace = "")
			String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findCilentInfoByServicesInParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindCilentInfoByServicesInParames")
	@ResponseWrapper(localName = "findCilentInfoByServicesInParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindCilentInfoByServicesInParamesResponse")
	public ResultReturn findCilentInfoByServicesInParames(
			@WebParam(name = "arg0", targetNamespace = "")
			CilentInfoServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findProInfoByServicesInParames", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindProInfoByServicesInParames")
	@ResponseWrapper(localName = "findProInfoByServicesInParamesResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindProInfoByServicesInParamesResponse")
	public ResultReturnByArray findProInfoByServicesInParames(
			@WebParam(name = "arg0", targetNamespace = "")
			ProInfoServicesIn arg0,
			@WebParam(name = "arg1", targetNamespace = "")
			int arg1, @WebParam(name = "arg2", targetNamespace = "")
			int arg2);

	/**
	 * 
	 * @return returns com.wisoft.wims.ResultReturnByArray
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllCilentInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllCilentInfo")
	@ResponseWrapper(localName = "findAllCilentInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllCilentInfoResponse")
	public ResultReturnByArray findAllCilentInfo();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "startTasks", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.StartTasks")
	@ResponseWrapper(localName = "startTasksResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.StartTasksResponse")
	public BaseReturn startTasks(@WebParam(name = "arg0", targetNamespace = "")
	List<WimsTaskmgr> arg0);

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findAllTrackCounts", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllTrackCounts")
	@ResponseWrapper(localName = "findAllTrackCountsResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.FindAllTrackCountsResponse")
	public int findAllTrackCounts();

	/**
	 * 
	 * @param arg0
	 * @return returns com.wisoft.wims.BaseReturn
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "printProInfo", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintProInfo")
	@ResponseWrapper(localName = "printProInfoResponse", targetNamespace = "http://www.springframework.org/schema/beans", className = "com.wisoft.wims.PrintProInfoResponse")
	public BaseReturn printProInfo(
			@WebParam(name = "arg0", targetNamespace = "")
			List<String> arg0);

}
